Improve install script; Allow erlang configure options

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -4,36 +4,108 @@ install_erlang() {
   local install_type=$1
   local version=$2
   local install_path=$3
-  local source_path=$(get_download_file_path $install_type $version)
 
-  download_source $install_type $version
+  if [ "$TMPDIR" = "" ]; then
+    local tmp_download_dir=$(mktemp -d)
+  else
+    local tmp_download_dir=$TMPDIR
+  fi
+
+  local source_path=$(get_download_file_path $install_type $version $tmp_download_dir)
+  download_source $install_type $version $source_path
 
   # running this in a subshell
   # because we don't want to disturb current working dir
   (
     cd $(dirname $source_path)
     tar zxf $source_path || exit 1
-    cd $(untar_path $install_type $version)
+    cd $(untar_path $install_type $version $tmp_download_dir)
+
     if [ "$install_type" != "version" ]
     then
       ./otp_build autoconf || exit 1
     fi
-    ./configure --prefix=$install_path || exit 1
+
+    local configure_options="$(construct_configure_options)"
+    # set in os_based_configure_options
+    # we unset it here because echo-ing changes the return value of the function
+    unset ASDF_PKG_MISSING
+
+    echo "Building with options: $configure_options"
+    ./configure $configure_options || exit 1
     make || exit 1
     make install || exit 1
   )
 }
 
 
+construct_configure_options() {
+  if [ "$ERLANG_CONFIGURE_OPTIONS" = "" ]; then
+    local configure_options="$(os_based_configure_options) --prefix=$install_path"
+
+    if [ "$ERLANG_EXTRA_CONFIGURE_OPTIONS" != "" ]; then
+      configure_options="$configure_options $ERLANG_EXTRA_CONFIGURE_OPTIONS"
+    fi
+  else
+    local configure_options="$ERLANG_CONFIGURE_OPTIONS --prefix=$install_path"
+  fi
+
+  echo "$configure_options"
+}
+
+
+homebrew_package_path() {
+  local package_name=$1
+
+  if [ "$(brew ls --versions $package_name)" = "" ]; then
+    echo ""
+  else
+    echo "$(brew --prefix $package_name)"
+  fi
+}
+
+
+exit_if_homebrew_not_installed() {
+  if [ "$(brew --version 2>/dev/null)" = "" ]; then
+    echo "ERROR: Please install homebrew for OSX"
+    exit 1
+  fi
+}
+
+
+os_based_configure_options() {
+  local operating_system=$(uname -a)
+  local configure_options=""
+
+  if [[ "$operating_system" =~ "Darwin" ]]; then
+    exit_if_homebrew_not_installed
+
+    configure_options="$configure_options --enable-darwin-universal"
+    local openssl_path=$(homebrew_package_path openssl)
+  else
+    local openssl_path=/usr
+  fi
+
+  if [ "$openssl_path" = "" ]; then
+    export ASDF_PKG_MISSING="openssl"
+  else
+    configure_options="$configure_options --with-ssl=$openssl_path"
+  fi
+
+  echo $configure_options
+}
+
+
 untar_path() {
   local install_type=$1
   local version=$2
+  local tmp_download_dir=$3
 
   if [ "$install_type" = "version" ]
   then
-    echo "$TMPDIR/otp_src_${version}"
+    echo "$tmp_download_dir/otp_src_${version}"
   else
-    echo "$TMPDIR/otp-${version}"
+    echo "$tmp_download_dir/otp-${version}"
   fi
 }
 
@@ -41,7 +113,7 @@ untar_path() {
 download_source() {
   local install_type=$1
   local version=$2
-  local download_path=$(get_download_file_path $install_type $version)
+  local download_path=$3
   local download_url=$(get_download_url $install_type $version)
 
   curl -Lo $download_path -C - $download_url
@@ -51,9 +123,10 @@ download_source() {
 get_download_file_path() {
   local install_type=$1
   local version=$2
+  local tmp_download_dir=$3
   local pkg_name="otp-${install_type}-${version}-src.tar.gz"
 
-  echo "$TMPDIR$pkg_name"
+  echo "$tmp_download_dir/$pkg_name"
 }
 
 
